name: MusicPlayer
options:
  bundleIdPrefix: com.fariszolj
  deploymentTarget:
    iOS: "16.0"

settings:
  SWIFT_VERSION: "5.9"

targets:
  MusicPlayer:
    type: application
    platform: iOS
    info:
      path: Info.plist
    sources:
      - path: .
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fariszolj.MusicPlayer
      INFOPLIST_FILE: Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      TARGETED_DEVICE_FAMILY: "1"
